version: '3'
services:
  db:
    image: mongo:latest
    command: mongod --smallfiles

  web:
    build:
      context: .
    working_dir: /mnt/rails
    env_file: .env
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/mnt/rails
    ports:
      - "3000:5000"
    links:
      - db
    depends_on:
      - db


